{{- if .Values.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "slackmoji-notifier.fullname" . }}
  labels:
    {{- include "slackmoji-notifier.labels" . | nindent 4 }}
type: Opaque
data:
  SLACK_BOT_TOKEN: {{ .Values.secret.slack.botToken | b64enc }}
  SLACK_APP_TOKEN: {{ .Values.secret.slack.appToken | b64enc }}
  {{- if .Values.secret.openai.apiKey }}
  OPENAI_API_KEY: {{ .Values.secret.openai.apiKey | b64enc }}
  {{- end }}
  {{- if .Values.secret.anthropic.apiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secret.anthropic.apiKey | b64enc }}
  {{- end }}
  {{- if .Values.secret.googleai.apiKey }}
  GOOGLEAI_API_KEY: {{ .Values.secret.googleai.apiKey | b64enc }}
  {{- end }}
{{- end }}
