---
name: tests

on: pull_request_target

jobs:

  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository &&
      'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: "true"

  # for pre-commit
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true
      - run: |
          make install-golangci-lint
      - uses: pre-commit/action@v3.0.0
